name: CI/CD Deploy

on:
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create directory if not exists
        run: |
          mkdir -p /home/Anthony/myapp

      - name: Clean old files
        run: |
          rm -rf /home/Anthony/myapp/*
          
      - name: Copy files to target directory
        run: |
          cp -r . /home/Anthony/myapp
